using AutoMapper;
using BaseCleanArchitecture.Application.DTOs;
using BaseCleanArchitecture.Application.DTOs.Articulo;
using BaseCleanArchitecture.Domain.Entities;

namespace BaseCleanArchitecture.Application.Mappings;

public class ArticuloMappingProfile : Profile
{
    public ArticuloMappingProfile()
    {
        CreateMap<Articulo, ArticuloDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
            .ForMember(dest => dest.Descripcion, opt => opt.MapFrom(src => src.Descripcion))
            .ForMember(dest => dest.IdMarca, opt => opt.MapFrom(src => src.IdMarca))
            .ForMember(dest => dest.IdModelo, opt => opt.MapFrom(src => src.IdModelo))
            .ForMember(dest => dest.Material, opt => opt.MapFrom(src => src.Material))
            .ForMember(dest => dest.Resistencia, opt => opt.MapFrom(src => src.Resistencia))
            .ForMember(dest => dest.Duracion, opt => opt.MapFrom(src => src.Duracion))
            .ForMember(dest => dest.Compatibilidad, opt => opt.MapFrom(src => src.Compatibilidad))
            .ForMember(dest => dest.PrecioUnitario, opt => opt.MapFrom(src => src.PrecioUnitario))
            .ForMember(dest => dest.PrecioVentanilla, opt => opt.MapFrom(src => src.PrecioVentanilla))
            .ForMember(dest => dest.CodigoBarras, opt => opt.MapFrom(src => src.CodigoBarras))
            .ForMember(dest => dest.Serie, opt => opt.MapFrom(src => src.Serie))
            .ForMember(dest => dest.PesoPieza, opt => opt.MapFrom(src => src.PesoPieza))
            .ForMember(dest => dest.Lote, opt => opt.MapFrom(src => src.Lote))
            .ForMember(dest => dest.FechaLote, opt => opt.MapFrom(src => src.FechaLote))
            .ForMember(dest => dest.PiezasCaja, opt => opt.MapFrom(src => src.PiezasCaja))
            .ForMember(dest => dest.TiempoVida, opt => opt.MapFrom(src => src.TiempoVida))
            .ForMember(dest => dest.Factura, opt => opt.MapFrom(src => src.Factura))
            .ForMember(dest => dest.Activo, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.DateCreate, opt => opt.MapFrom(src => src.DateCreate))
            .ForMember(dest => dest.DateUpdate, opt => opt.MapFrom(src => src.DateUpdate))
            .ForMember(dest => dest.IdUser, opt => opt.MapFrom(src => src.IdUser))
            .ForMember(dest => dest.IdUserUpdate, opt => opt.MapFrom(src => src.IdUserUpdate));

        CreateMap<CreateArticuloDto, Articulo>()
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
            .ForMember(dest => dest.Descripcion, opt => opt.MapFrom(src => src.Descripcion))
            .ForMember(dest => dest.IdMarca, opt => opt.MapFrom(src => src.IdMarca))
            .ForMember(dest => dest.IdModelo, opt => opt.MapFrom(src => src.IdModelo))
            .ForMember(dest => dest.Material, opt => opt.MapFrom(src => src.Material))
            .ForMember(dest => dest.Resistencia, opt => opt.MapFrom(src => src.Resistencia))
            .ForMember(dest => dest.Duracion, opt => opt.MapFrom(src => src.Duracion))
            .ForMember(dest => dest.Compatibilidad, opt => opt.MapFrom(src => src.Compatibilidad))
            .ForMember(dest => dest.PrecioUnitario, opt => opt.MapFrom(src => src.PrecioUnitario))
            .ForMember(dest => dest.PrecioVentanilla, opt => opt.MapFrom(src => src.PrecioVentanilla))
            .ForMember(dest => dest.CodigoBarras, opt => opt.MapFrom(src => src.CodigoBarras))
            .ForMember(dest => dest.Serie, opt => opt.MapFrom(src => src.Serie))
            .ForMember(dest => dest.PesoPieza, opt => opt.MapFrom(src => src.PesoPieza))
            .ForMember(dest => dest.Lote, opt => opt.MapFrom(src => src.Lote))
            .ForMember(dest => dest.PiezasCaja, opt => opt.MapFrom(src => src.PiezasCaja))
            .ForMember(dest => dest.TiempoVida, opt => opt.MapFrom(src => src.TiempoVida))
            .ForMember(dest => dest.Factura, opt => opt.MapFrom(src => src.Factura))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => true));

        CreateMap<UpdateArticuloDto, Articulo>()
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
            .ForMember(dest => dest.Descripcion, opt => opt.MapFrom(src => src.Descripcion))
            .ForMember(dest => dest.IdMarca, opt => opt.MapFrom(src => src.IdMarca))
            .ForMember(dest => dest.IdModelo, opt => opt.MapFrom(src => src.IdModelo))
            .ForMember(dest => dest.Material, opt => opt.MapFrom(src => src.Material))
            .ForMember(dest => dest.Resistencia, opt => opt.MapFrom(src => src.Resistencia))
            .ForMember(dest => dest.Duracion, opt => opt.MapFrom(src => src.Duracion))
            .ForMember(dest => dest.Compatibilidad, opt => opt.MapFrom(src => src.Compatibilidad))
            .ForMember(dest => dest.PrecioUnitario, opt => opt.MapFrom(src => src.PrecioUnitario))
            .ForMember(dest => dest.PrecioVentanilla, opt => opt.MapFrom(src => src.PrecioVentanilla))
            .ForMember(dest => dest.CodigoBarras, opt => opt.MapFrom(src => src.CodigoBarras))
            .ForMember(dest => dest.Serie, opt => opt.MapFrom(src => src.Serie))
            .ForMember(dest => dest.PesoPieza, opt => opt.MapFrom(src => src.PesoPieza))
            .ForMember(dest => dest.Lote, opt => opt.MapFrom(src => src.Lote))
            .ForMember(dest => dest.PiezasCaja, opt => opt.MapFrom(src => src.PiezasCaja))
            .ForMember(dest => dest.TiempoVida, opt => opt.MapFrom(src => src.TiempoVida))
            .ForMember(dest => dest.Factura, opt => opt.MapFrom(src => src.Factura));

        CreateMap<Articulo, ArticuloResponseDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
            .ForMember(dest => dest.Descripcion, opt => opt.MapFrom(src => src.Descripcion))
            .ForMember(dest => dest.IdMarca, opt => opt.MapFrom(src => src.IdMarca))
            .ForMember(dest => dest.IdModelo, opt => opt.MapFrom(src => src.IdModelo))
            .ForMember(dest => dest.Material, opt => opt.MapFrom(src => src.Material))
            .ForMember(dest => dest.Resistencia, opt => opt.MapFrom(src => src.Resistencia))
            .ForMember(dest => dest.Duracion, opt => opt.MapFrom(src => src.Duracion))
            .ForMember(dest => dest.Compatibilidad, opt => opt.MapFrom(src => src.Compatibilidad))
            .ForMember(dest => dest.PrecioUnitario, opt => opt.MapFrom(src => src.PrecioUnitario))
            .ForMember(dest => dest.PrecioVentanilla, opt => opt.MapFrom(src => src.PrecioVentanilla))
            .ForMember(dest => dest.CodigoBarras, opt => opt.MapFrom(src => src.CodigoBarras))
            .ForMember(dest => dest.Serie, opt => opt.MapFrom(src => src.Serie))
            .ForMember(dest => dest.PesoPieza, opt => opt.MapFrom(src => src.PesoPieza))
            .ForMember(dest => dest.Lote, opt => opt.MapFrom(src => src.Lote))
            .ForMember(dest => dest.FechaLote, opt => opt.MapFrom(src => src.FechaLote))
            .ForMember(dest => dest.PiezasCaja, opt => opt.MapFrom(src => src.PiezasCaja))
            .ForMember(dest => dest.TiempoVida, opt => opt.MapFrom(src => src.TiempoVida))
            .ForMember(dest => dest.Factura, opt => opt.MapFrom(src => src.Factura))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.DateCreate, opt => opt.MapFrom(src => src.DateCreate))
            .ForMember(dest => dest.IdUser, opt => opt.MapFrom(src => src.IdUser))
            .ForMember(dest => dest.DateUpdate, opt => opt.MapFrom(src => src.DateUpdate))
            .ForMember(dest => dest.IdUserUpdate, opt => opt.MapFrom(src => src.IdUserUpdate));

        CreateMap<Articulo, CreateArticuloResponseDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
            .ForMember(dest => dest.Descripcion, opt => opt.MapFrom(src => src.Descripcion))
            .ForMember(dest => dest.IdMarca, opt => opt.MapFrom(src => src.IdMarca))
            .ForMember(dest => dest.IdModelo, opt => opt.MapFrom(src => src.IdModelo))
            .ForMember(dest => dest.Material, opt => opt.MapFrom(src => src.Material))
            .ForMember(dest => dest.Resistencia, opt => opt.MapFrom(src => src.Resistencia))
            .ForMember(dest => dest.Duracion, opt => opt.MapFrom(src => src.Duracion))
            .ForMember(dest => dest.Compatibilidad, opt => opt.MapFrom(src => src.Compatibilidad))
            .ForMember(dest => dest.PrecioUnitario, opt => opt.MapFrom(src => src.PrecioUnitario))
            .ForMember(dest => dest.PrecioVentanilla, opt => opt.MapFrom(src => src.PrecioVentanilla))
            .ForMember(dest => dest.CodigoBarras, opt => opt.MapFrom(src => src.CodigoBarras))
            .ForMember(dest => dest.Serie, opt => opt.MapFrom(src => src.Serie))
            .ForMember(dest => dest.PesoPieza, opt => opt.MapFrom(src => src.PesoPieza))
            .ForMember(dest => dest.Lote, opt => opt.MapFrom(src => src.Lote))
            .ForMember(dest => dest.FechaLote, opt => opt.MapFrom(src => src.FechaLote))
            .ForMember(dest => dest.PiezasCaja, opt => opt.MapFrom(src => src.PiezasCaja))
            .ForMember(dest => dest.TiempoVida, opt => opt.MapFrom(src => src.TiempoVida))
            .ForMember(dest => dest.Factura, opt => opt.MapFrom(src => src.Factura))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.DateCreate, opt => opt.MapFrom(src => src.DateCreate))
            .ForMember(dest => dest.IdUser, opt => opt.MapFrom(src => src.IdUser));

        CreateMap<Articulo, UpdateArticuloResponseDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre))
            .ForMember(dest => dest.Descripcion, opt => opt.MapFrom(src => src.Descripcion))
            .ForMember(dest => dest.IdMarca, opt => opt.MapFrom(src => src.IdMarca))
            .ForMember(dest => dest.IdModelo, opt => opt.MapFrom(src => src.IdModelo))
            .ForMember(dest => dest.Material, opt => opt.MapFrom(src => src.Material))
            .ForMember(dest => dest.Resistencia, opt => opt.MapFrom(src => src.Resistencia))
            .ForMember(dest => dest.Duracion, opt => opt.MapFrom(src => src.Duracion))
            .ForMember(dest => dest.Compatibilidad, opt => opt.MapFrom(src => src.Compatibilidad))
            .ForMember(dest => dest.PrecioUnitario, opt => opt.MapFrom(src => src.PrecioUnitario))
            .ForMember(dest => dest.PrecioVentanilla, opt => opt.MapFrom(src => src.PrecioVentanilla))
            .ForMember(dest => dest.CodigoBarras, opt => opt.MapFrom(src => src.CodigoBarras))
            .ForMember(dest => dest.Serie, opt => opt.MapFrom(src => src.Serie))
            .ForMember(dest => dest.PesoPieza, opt => opt.MapFrom(src => src.PesoPieza))
            .ForMember(dest => dest.Lote, opt => opt.MapFrom(src => src.Lote))
            .ForMember(dest => dest.FechaLote, opt => opt.MapFrom(src => src.FechaLote))
            .ForMember(dest => dest.PiezasCaja, opt => opt.MapFrom(src => src.PiezasCaja))
            .ForMember(dest => dest.TiempoVida, opt => opt.MapFrom(src => src.TiempoVida))
            .ForMember(dest => dest.Factura, opt => opt.MapFrom(src => src.Factura))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.DateCreate, opt => opt.MapFrom(src => src.DateCreate))
            .ForMember(dest => dest.IdUser, opt => opt.MapFrom(src => src.IdUser))
            .ForMember(dest => dest.DateUpdate, opt => opt.MapFrom(src => src.DateUpdate))
            .ForMember(dest => dest.IdUserUpdate, opt => opt.MapFrom(src => src.IdUserUpdate));

        CreateMap<Articulo, ArticuloSimpleDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre));

        // Mapeos para comboboxes
        CreateMap<Marca, MarcaSimpleDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.Nombre, opt => opt.MapFrom(src => src.Nombre));

        // Note: ModeloDto doesn't exist, you may need to create it or remove this mapping
        // CreateMap<Modelo, ModeloDto>()
        //     .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
        //     .ForMember(dest => dest.NombreModelo, opt => opt.MapFrom(src => src.NombreModelo));
    }
} 